---
title: Rhode Island COVID-19 Community Resources
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
description: Resourses and supports for folks grappling with the COVID19 crisis in
  Rhode Island. Organized by the AMOR Network.
Background Color: "#e43a24"
Accent Color: "#fbff00"
Menu Image: 
Site Logo: "/uploads/AMOR-LOGO_2.png"
Favicon Image: "/uploads/AMOR-favicon.png"
baseurl: 
url: http://mutualaidri.com
markdown: kramdown
